Kartoffelsalat hinzugefügt
SanJSp/Lets_git_kochbuch pull request #11
Opened 2020-06-24 13:27 UTC by jfkoeln

Es wurde ein Rheinischer Kartoffelsalat bei den Salaten hinzugefügt.

fixes: #2

2020-06-24 15:39 UTC, verspaeteterZug approved these changes
Sehr Gut!

2020-06-24 15:39 UTC, BS-scripter commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +Auflistung der Zutaten mit Menge davor z.B.
Ist das da bewusst oder einfach nur vergessen zu entfernen?

2020-06-24 18:01 UTC, tad3u5 requested changes
Dies ist meine erste Review. Ich bin noch dabei mich in Github zurecht zu finden.

2020-06-24 18:01 UTC, tad3u5 commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +1. Kartoffeln waschen und in Salzwasser ca. 20 Minuten kochen. Kartoffeln abgießen, etwas abkühlen lassen und pellen. Wurst und gekochte Eier pellen. Gurken abtropfen lassen. Kartoffeln, Fleischwurst
Bitte die "11/2" in "1 1/2" oder "1,5" ändern.

2020-06-24 18:01 UTC, tad3u5 commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +* 1EL Zucker
aus 1EL wird 1 EL

2020-06-24 18:01 UTC, tad3u5 commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +1. Kartoffeln waschen und in Salzwasser ca. 20 Minuten kochen. Kartoffeln abgießen, etwas abkühlen lassen und pellen. Wurst und gekochte Eier pellen. Gurken abtropfen lassen. Kartoffeln, Fleischwurst
Ich kenne diesen Kartoffelsalat nicht. Könnten es auch einfach nur "1/2 cm große Würfel" sein?

2020-06-24 19:06 UTC, jfkoeln commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +Auflistung der Zutaten mit Menge davor z.B.
opps, natürlich vergessen, aber so kann auch noch mal das Verfahren geübt werden, eine Korrektur zu einem PR abzuliefern.

2020-06-24 19:07 UTC, jfkoeln commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +1. Kartoffeln waschen und in Salzwasser ca. 20 Minuten kochen. Kartoffeln abgießen, etwas abkühlen lassen und pellen. Wurst und gekochte Eier pellen. Gurken abtropfen lassen. Kartoffeln, Fleischwurst
es müsste 1,5 cm große Würfel heißen. Das kommt davon, wenn man zu schnell ohne Sorgfalt kopiert :-(

2020-06-24 19:15 UTC, jfkoeln commented
Habe die genannten Verbesserungsvorschläge eingearbeitet.

2020-06-24 19:16 UTC, jfkoeln commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +1. Kartoffeln waschen und in Salzwasser ca. 20 Minuten kochen. Kartoffeln abgießen, etwas abkühlen lassen und pellen. Wurst und gekochte Eier pellen. Gurken abtropfen lassen. Kartoffeln, Fleischwurst
erledigt

2020-06-24 19:16 UTC, jfkoeln commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +* 1EL Zucker
erledigt

2020-06-24 20:56 UTC, tad3u5 approved these changes
So sieht das gut aus. Das Rezept werde ich mal probieren.

2020-06-25 08:17 UTC, SanJSp requested changes

2020-06-25 08:17 UTC, SanJSp commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +3. Dressing unter den Salat heben und ca. 60 Minuten ziehen lassen. Schnittlauch waschen, trocken schütteln und in Röllchen schneiden. Über den Salat streuen.
Ich würde mir wünschen, dass die einzelnen Schritte noch in kleinere Schritte gepackt werden. Zum Beispiel:
1. Kartoffeln waschen und in Salzwasser ca. 20 Minuten kochen.
2. Kartoffeln abgießen, etwas abkühlen lassen und pellen. 
3. Wurst und gekochte Eier pellen. Gurken abtropfen lassen. Kartoffeln, Fleischwurst, Gurken und Eier in ca. 1 1⁄2 cm große Würfel schneiden. Alles in eine Schüssel geben.

2020-06-27 10:31 UTC, tad3u5 commented on Beilagen/Salate/RheinischerKartoffelsalat.md
> +gibt es leider keines
Wenn es kein Bild gibt, braucht es auch keine Überschrift. Sollte mal ein Bild hinzugefügt werden, kann man auch den Abschnitt Bild ergänzen.

Sonst sieht das Rezept sehr gut aus.

2020-06-29 17:02 UTC, ancchi reviewed
Da andere das auch so gemacht haben mit dem Bild und es jetzt kurz vor Kursende ist, denke ich, dass das okay ist.

2020-06-29 17:11 UTC, merged