Nusslebkuchen zugefügt
SanJSp/Lets_git_kochbuch pull request #13
Opened 2020-06-24 14:10 UTC by opayogi

ich stochere hier im Nebel.

kriege ich den verdammten Kuchen so hinein?

2020-06-24 14:14 UTC, opayogi commented
eigentlich dachte ich, ich könnte dies dem Isue #8 zuordnen ???

2020-06-24 14:20 UTC, jfkoeln commented
Dem Issue #4 kannst mit dem Eintrag: issue: #8 
hab noch einen Tippfehler gefunden: Cremig wird laut Duden mit c geschrieben.

Aber ansonsten bist Du auf dem richtigen Weg, über diesen PR bekommst Du dein Rezept hier rein. allerdings muss es nun durch eine berechtigte Person gemerged werden.

2020-06-24 14:53 UTC, opayogi commented
den Fehler hab ich korrigiert, daher neues Problem: es gibt jetzt 2 Pullrequests.
Und wo muss das fixes rein, etwa hier?
fixes: #8

2020-06-24 15:35 UTC, verspaeteterZug approved these changes
Gute Arbeit!

Um ehrlich zu sein bin ich mit der Formulierung "fressen" nicht ganz zufrieden, aber ich habe damit eigentlich kein Problem

2020-06-24 17:07 UTC, tad3u5 commented on Deserts/Kuchen/Nusslebkuchen.md
> +* 1 Paket Backpulver
Vielleicht ist für einige Backunkundige die Bezeichnung "_Paket_" Backpulver irreführend. Da sonst immer nur von Päckchen gesprochen wird und im normalen Supermarkt Backpulver auch nicht im 1 kg Paket verkauft wird. 

Ich schlage vor das "_Paket_" in "**Päckchen**" zu ändern.

2020-06-26 09:36 UTC, opayogi commented
habe Paket in Päckchen geändert, wie tad3u5 angemerkt.
Puderzucker und Rum mit Mengen zugefügt.
Unterteilt in Teig und Zuckerguss.
fixes: #8

2020-06-26 09:59 UTC, opayogi commented
Jetzt habe ich den Pull request geclosed, weil ich denke, dass von meiner Seite alles fertig ist.
War das richtig? Oder muss ich warten, bis das Rezept gemerged ist?
Jetzt wird "delete this fork" angeboten, muss ich das machen, damit es fertig wird, oder ist dann alles weg?

2020-06-26 14:35 UTC, SanJSp requested changes

2020-06-26 14:35 UTC, SanJSp commented on Deserts/Kuchen/Nusslebkuchen.md
> +Dies ist das Rezept für Gabi's Nusslebkuchen. Es eignet sich zum Backen, vorausgesetzt, man hat alle Zutaten und einen Backofen mit Backblech. Mit dem Teig werden kleine Plätzchen auf Oblaten gesetzt
Könntest du bitte hier noch statt fressen essen schreiben? Darüber würde ich mich freuen.

2020-06-26 15:23 UTC, opayogi commented on Deserts/Kuchen/Nusslebkuchen.md
> +Dies ist das Rezept für Gabi's Nusslebkuchen. Es eignet sich zum Backen, vorausgesetzt, man hat alle Zutaten und einen Backofen mit Backblech. Mit dem Teig werden kleine Plätzchen auf Oblaten gesetzt
wird gemacht, danke.

2020-06-27 10:23 UTC, tad3u5 commented
Der Pull request bleibt offen und wird reviewed und Verbesserungen eingebracht bis mehrere Reviewer ihr approved geben und Sandro bzw. ein Maintainer den Request mergen. Ist dann der PR im Master Branch aufgenommen, kannst du den Branch löschen.

Geschlossen werden PR wenn sie erfolgreich gemerged wurden oder sich ihr Zweck überholt hat.

2020-06-27 10:25 UTC, tad3u5 approved these changes

2020-06-28 12:59 UTC, SanJSp approved these changes

2020-06-28 12:59 UTC, merged