Chili-Guacamole-Rezept hinzugefügt
SanJSp/Lets_git_kochbuch pull request #27
Opened 2020-06-24 21:55 UTC by dangerousdani

Hier, wie versprochen mein super scharfes und leckeres Guacamole Rezept für die herzhaften Essen unter uns. Nun muss das Brot nicht trocken gegessen werden und alle werden satt :)

fixed: #24

2020-06-25 04:58 UTC, tad3u5 approved these changes

2020-06-25 08:12 UTC, SanJSp requested changes
Bitte die Leerzeichen nach den Markdown Zeichen einfügen

2020-06-25 08:12 UTC, SanJSp commented on Vorspeisen/Dips und Aufstriche/Chili-Guacamole.txt
> +#Chili-Guacamole
Bitte füge ein Leerzeichen nach den # und restlichen Markdown Zeichen ein

2020-06-26 15:36 UTC, tad3u5 requested changes
Stimmt, da muss auch ich mein Approve zurück nehmen. Das Markdown wird so nicht unterstützt. Zwischen den #, ## und * Zeichen und dem Text muss ein Leerzeichen stehen.

Was ich allerdings auch nicht weiß, ob für eine Markdown Darstellung die Dateiendung ein ".md" sein muss. Das könnte noch ein zusätzlicher Punkt sein.

2020-06-28 13:01 UTC, SanJSp commented
Stimmt, die Dateiendung ist wichtig! Bitte in .md ändern

2021-01-25 15:35 UTC, SanJSp commented
geschlossen, da inaktiv

2021-01-25 15:35 UTC, closed without merging