Add Mate-Limo (2.Versuch)
SanJSp/Lets_git_kochbuch pull request #28
Opened 2020-06-24 22:18 UTC by tad3u5

Fixes: #25
Also hier das Rezept zur Selbstbau **Hackerbrause.**

2020-06-25 08:18 UTC, SanJSp requested changes
Hallo @tad3u5 

vielen Dank für deinen Beitrag. Ich würde dich trotzdem bitten dich an die Formattierungsrichtlinien aus dem Beispielrezept zu halten. Bitte füge z.B. Überschriften ein.

2020-06-27 07:52 UTC, verspaeteterZug approved these changes

2020-06-27 07:52 UTC, BS-scripter commented on Getränke/Limonade/Mate-Limo.md
> ++ ***6 TL loser Mate-Tee (1 TL gespricht ca. 2g)***
Ich möchte mit diesem Kommentar eigentlich nur checken,wie die
+ ***Formatierung***
+ ***aussieht***

2020-06-27 10:02 UTC, tad3u5 commented on Getränke/Limonade/Mate-Limo.md
> ++ ***6 TL loser Mate-Tee (1 TL gespricht ca. 2g)***
Das + gibt die Aufzählung und die drei * führen zu dicker und kursiver Schreibweise.

2020-06-28 12:59 UTC, SanJSp approved these changes

2020-06-28 12:59 UTC, merged