Dotsch hinzugefügt
SanJSp/Lets_git_kochbuch pull request #38
Opened 2020-06-26 11:59 UTC by snowgrey

2020-06-26 13:15 UTC, kriskak commented on dotsch.md
> +* Butter (zum Ausstreichen der Form)
super, dass du dazugeschrieben hast wofü man die Butter braucht, das macht das Rezept echt übersichtlich!

2020-06-26 13:16 UTC, kriskak commented on dotsch.md
> +Bild wird noch nachgereicht...
Bin echt gespannt wie es aussieht, da ich noch nie davon gehört habe!

2020-06-26 13:29 UTC, Combot0 approved these changes

2020-06-26 14:37 UTC, SanJSp requested changes

2020-06-26 14:37 UTC, SanJSp commented on dotsch.md
> +Bild wird noch nachgereicht...
Entweder du fügst ein Bild hinzu oder löschst diesen Teil des Rezepts. Bitte korrigieren.

Liebe Grüße
Sandro

2020-06-27 10:43 UTC, snowgrey commented
Vielen Dank für das Feedback. Habe das Bild jetzt mal von meinem lokalen Verzeichnis in meinen Fork auf GitHub mittels push hochgeladen, wird das dann hier automatisch hier (im master?) aktualisiert oder muss ich nochmal ein pull request(? ) erstellen?

2020-06-27 10:58 UTC, snowgrey commented
fixes #38

2020-06-27 12:38 UTC, tad3u5 commented
Ja der Commit mit dem Bild ist da. Allerdings musst du noch den Link zum Bild in deinem Rezept setzten. Dort steht immernoch wird nachgereicht drin.

2020-06-27 14:23 UTC, snowgrey commented
> Ja der Commit mit dem Bild ist da. Allerdings musst du noch den Link zum Bild in deinem Rezept setzten. Dort steht immernoch wird nachgereicht drin.

Oh, sorry...hatte ganz vergessen, dass ich die Rezept-Datei ja auch nochmal committen muss...

2020-06-27 14:54 UTC, tad3u5 approved these changes
Alles klar. Das sollte passen. Ich danke Dir für dieses Rezept.

2020-06-28 12:56 UTC, SanJSp approved these changes

2020-06-28 12:56 UTC, merged