einfaches Lachsgericht hinzugefuegt
SanJSp/Lets_git_kochbuch pull request #40
Opened 2020-06-26 13:07 UTC by kriskak

Rezept "einfaches Lachsgericht" wurde auf dem working - Branch einfachesLachsgericht hinzugefügt.

2020-06-28 09:15 UTC, hjfriedrich requested changes
Vielen Dank für das schöne Rezept. Ich habe aber noch ein paar Fragen und Fehler entdeckt:
Mir ist nicht ganz klar, wieso du die -> Kombination im Fließtext der Einleitung verwendest. Ich empfehle, sie entweder zu entfernen oder es mit einem entsprechenden HTML-Entity zu versuchen, beispielsweise &rAarr;
Heferl kenne ich als Haferl. Da man das Wort eher regional verwendet, empfehle ich den Begriff Tasse.
Nach Ebly, vor der Klammer auf fehlt ein Leerzeichen.
Anleitung Punkt 4: Fillet müsste Filet heißen
Punkt 6: Der Abkürzungspunkt hinter ca fehlt. Minuten und Umdrehen bitte groß.

2020-06-28 20:18 UTC, kriskak commented
Danke für den Review! Ich werde die gewünschten Änderungen vornehmen.

2020-06-28 20:49 UTC, kriskak commented
Habe die gewünschten Änderungen vorgenommen! 
Commit ist bereit gemerged zu werden.

2020-06-29 13:50 UTC, hjfriedrich approved these changes
Vielen Dank für die Änderungen.

2020-06-29 17:27 UTC, merged