Ordner Backwaren hinzugefügt
SanJSp/Lets_git_kochbuch pull request #46
Opened 2020-06-26 20:00 UTC by hahabl

Ich habe den Ordner Backwaren hinzugefügt

fixes: #19

2020-06-26 20:25 UTC, verspaeteterZug approved these changes

2020-06-28 19:02 UTC, hahabl commented
Aber den Merge kann ich jetzt nicht durchführen, oder? Zumindest sehe ich dafür keinen Button.

2020-06-29 17:33 UTC, ancchi requested changes
Hallo hahabl,
du kannst selber eine Datei nicht mergen. Das machen die Projekt-Owner (SanJSp) oder Berechtigte, die vorher einen Review durchgeführt haben.
Um das Issue zu erfüllen, solltest du noch die .md-Datei mit dem Rezept hinzufügen. Sonst gilt es nicht als erfüllt und kann nicht geschlossen werden. Der Ordner kann bestehen bleiben.

2020-06-30 19:34 UTC, hahabl commented
Hallo ancchi,
Danke für die Antwort. Nun habe ich ein Rezept in den Ordner Backwaren hinzugefügt.

Aber so ganz verstehe ich es nicht. Denn z.B. in anderen Ordnern (z.B. Snacks) gibt es auch nur eine Datei "Hier könnte dein Müsliriegel stehen.md.txt". Und so eine Datei war ja schon drin in meiner ersten Version vom Ordner Backwaren.
Und in dem ersten Schritt sollte ja nur die Struktur (also der Ordner) angelegt werden, so dass dort dann Rezepte abgelegt werden können. Mit diesem Anlegen des Ordners sollte ich doch nicht gezwungen werden auch gleich das erste Rezept zu liefern, oder?

Oder habe ich das falsch verstanden? ist ja schließlich alles Neuland hier :-)

2020-06-30 19:51 UTC, ancchi commented
Verstehe ich jetzt selbst grad nicht mehr. Ich war der Meinung, dass das Issue den Auftrag beinhaltete, dass ein Rezept für eine Backware erstellt werden sollte. Da sollte ja tatsächlich nur der Ordner angelegt werden. Sorry, mein Fehler.

2020-06-30 19:52 UTC, merged