Apfelkuchen
SanJSp/Lets_git_kochbuch pull request #52
Opened 2020-06-27 16:10 UTC by petrabuehh

Rezept für einen Apfelkuchen vom Blech hinzugefügt (2 neue Dateien, siehe unten).
Bitte prüfen und übernehmen.
Vielen Dank!

2020-06-27 17:13 UTC, tad3u5 requested changes

2020-06-27 17:13 UTC, tad3u5 commented on Desserts/Kuchen/Apfelkuchen.md
> +Der Apfelkuchen wird anschließend im vorgeheizten Ofen (175 Grad, Ober- und unterhitze) ca. 45 Minuten gebacken.
Wenn du noch die Unterhitze groß schreibst sollte alles für den Merge bereit sein.

Ich Danke dir für das Rezept.

2020-06-28 16:14 UTC, tad3u5 approved these changes

2020-06-28 20:50 UTC, verspaeteterZug approved these changes

2020-06-29 12:44 UTC, merged