Create Darjeeling Lazy Afternoon Lemonade
SanJSp/Lets_git_kochbuch pull request #79
Opened 2020-06-29 21:13 UTC by katrine-github

Hallo zusammen, 
wie findet ihr das Rezept für den Cocktail #77 ?

2020-06-29 22:06 UTC, doroGrund commented
Vielleicht magst du noch einen Tipp hinzufügen, was Jameson ist? Ich weiß es nicht.

2020-06-29 22:16 UTC, ancchi requested changes
Sieht lecker aus. Aber meintest du bei der Zubereitung Whisky anstatt Whilsy?? :-D

2020-06-30 07:08 UTC, katrine-github commented
Vielen Dank für die guten Anmerkungen. Ich würde beim Rezept noch einen Wikipedia-Link für die Whiskybrennerei „Jameson“ einfügen. Außerdem bessere ich den Tippfehler noch aus aus (Whilsy schmeckt bestimmt nicht so gut wie Whisky ;-) ).

2020-06-30 15:57 UTC, ancchi approved these changes
Das mit dem Wiki-Eintrag find ich cool. ^^
Kann jetzt germerget werden. :)

2020-06-30 15:57 UTC, merged